import { Braces, Check, Copy, Download, FileJson, PlugZap, ShieldCheck, ArrowRight, RefreshCw } from 'lucide-react'
import { useState } from 'react'
import { BASE, request } from '../../api/client'
import { sample } from '../../test/fixtures/sample'
export default function IntegrationPage() {
  const [copied, setCopied] = useState(false)
  const [error, setError] = useState('')
  const command = `curl -X POST http://127.0.0.1:8010${BASE}/ingest \\\n  -H "Authorization: Bearer <INTEGRATION_KEY>" \\\n  -H "Content-Type: application/json" \\\n  --data-binary @invoice.json`
  async function schema() {
    try {const response = await request('/schema'); const blob = await response.blob(); const url = URL.createObjectURL(blob); const a = document.createElement('a'); a.href = url; a.download = 'aiva-snapshot.schema.json'; a.click(); setTimeout(() => URL.revokeObjectURL(url), 1000)} catch (e) {setError((e as Error).message)}
  }
  return <div className="integration-page"><div className="eyebrow">CONNECTED WORKSPACE</div><h1>เชื่อมต่อระบบของคุณ</h1><p className="page-description">ส่งข้อมูลที่ประมวลผลแล้วมาแสดงใน AIVA ผ่าน JSON API และแนบ PDF แยกได้</p>
    <div className="integration-flow"><div><div className="mini-icon"><Braces/></div><b>ระบบต้นทาง</b><span>OCR / ERP / ระบบเอกสาร</span></div><ArrowRight/><div><div className="mini-icon"><PlugZap/></div><b>JSON API</b><span>ตรวจรูปแบบ · เก็บแต่ละรุ่น</span></div><ArrowRight/><div><div className="mini-icon"><FileJson/></div><b>AIVA Portal</b><span>ค้นหา · อ่านข้อมูล · ดู PDF</span></div></div>
    <div className="integration-grid"><section className="panel"><div className="panel-heading"><h3>1. ส่งข้อมูลเอกสาร</h3><span className="method">POST</span></div><code className="endpoint">{BASE}/ingest</code><p>ใช้ event_id เดิมเมื่อส่งซ้ำ และเพิ่ม revision เมื่อปรับข้อมูลเอกสารเดิม ระบบจะไม่เขียนทับด้วย revision ที่เก่ากว่า</p><div className="code-toolbar"><span>ตัวอย่างคำขอ</span><button className="text-button" onClick={async () => {try {await navigator.clipboard.writeText(command); setCopied(true)} catch {setError('คัดลอกไม่ได้ กรุณาเลือกข้อความและคัดลอกเอง')}}}>{copied ? <Check size={15}/> : <Copy size={15}/>} {copied ? 'คัดลอกแล้ว' : 'คัดลอก'}</button></div><pre className="integration-code">{command}</pre><a className="text-button" href="http://127.0.0.1:8010/api/docs" target="_blank" rel="noreferrer">เปิด Swagger ในเครื่องนี้ <ArrowRight size={14}/></a></section>
    <section className="panel"><div className="panel-heading"><h3>2. แนบไฟล์ PDF</h3><span className="method">POST</span></div><code className="endpoint">/documents/&#123;id&#125;/pdf?revision=1</code><p>ใช้ id ที่ได้จากขั้นตอนแรก ส่ง multipart/form-data โดยใช้ชื่อฟิลด์ file ขนาดไม่เกิน 20 MB และไม่เกิน 500 หน้า ระบบเก็บ PDF แยกตาม revision ที่ระบุ</p><div className="notice info">ไม่รับ URL ภายนอกโดยอัตโนมัติ กรุณาส่งไฟล์ PDF ผ่าน API หรือแนบผ่านหน้าเอกสาร</div><div className="requirements"><ShieldCheck size={20}/><div><b>API key แยกตามช่องทาง</b><p>Integration key สำหรับส่งข้อมูล<br/>Portal key สำหรับ workspace<br/>ยังไม่มีสิทธิ์แยกตามผู้ใช้หรือบริษัท</p></div></div></section></div>
    <section className="panel action-outbox-guide"><div className="panel-heading"><div><h3>3. รับคำขอจากผู้ตรวจ</h3><p>ใช้ Integration key อ่านคำขอส่งตรวจซ้ำ แล้วตอบรับก่อนส่ง revision ใหม่กลับมา</p></div><RefreshCw size={19}/></div><div className="outbox-endpoints"><div><span className="method">GET</span><code>{BASE}/action-requests?status=pending</code><p>อ่าน resubmit/rerun ที่รอระบบต้นทาง</p></div><ArrowRight/><div><span className="method">POST</span><code>{BASE}/action-requests/&#123;id&#125;/ack</code><p>ตอบ accepted หรือ failed</p></div><ArrowRight/><div><span className="method">POST</span><code>{BASE}/ingest</code><p>ส่ง revision ใหม่พร้อมผลตรวจจริง</p></div></div><div className="notice info">การตอบ accepted หมายถึงรับคำขอเข้าคิวแล้ว สถานะ Portal จะยังรอผลตรวจจนกว่าจะได้รับ snapshot revision ใหม่</div></section>
    <section className="panel"><div className="panel-heading"><div><h3>JSON contract <span className="tag">v1.0</span></h3><p>ตัวอย่างสังเคราะห์ · สถานะและผลตรวจมาจากระบบต้นทาง</p></div><button className="button secondary" onClick={schema}><Download size={16}/> ดาวน์โหลด Schema</button></div>{error && <div className="notice danger">{error}</div>}<pre className="json-preview sample-json">{JSON.stringify(sample, null, 2)}</pre></section>
  </div>
}
