export type Status = 'Auto-pass' | 'Review' | 'Hold' | 'Manual Review' | 'Duplicate' | 'Confirmed' | 'Posted' | 'Rejected'
export type Invoice = {invoice_num: string; supplier_name: string; company: string; invoice_date?: string | null; po_number?: string | null; release_num?: string | null; supplier_tax_id?: string | null; customer_tax_id?: string | null; currency: string; sub_total?: string | null; vat?: string | null; grand_total?: string | null}
export type Rule = {rule_id: string; result: 'pass' | 'fail' | 'manual_review' | 'not_evaluated'; exception_code?: string | null; severity?: string | null; evidence?: string | null; page?: number | null}
export type Line = {description: string; quantity?: string | null; uom?: string | null; unit_price?: string | null; amount?: string | null; receipt_line?: string | null; receipt_qty?: string | null; receipt_price?: string | null; match_level?: string | null}
export type Receipt = {receipt_num?: string | null; org_id?: string | null; receiver?: string | null; receipt_total?: string | null}
export type Snapshot = {schema_version: '1.0'; event_id: string; source_system: string; external_id: string; revision: number; standard_version: string; status: Status; invoice: Invoice; receipt?: Receipt | null; rules: Rule[]; lines: Line[]; note?: string | null}
export type RevisionSummary = {revision: number; status: Status; received_at: string; event_id: string; pdf: {available: boolean; pages: number | null}}
export type ActionName = 'explain' | 'resubmit' | 'rerun' | 'return' | 'reject' | 'hold' | 'confirm'
export type ActionReason = {code: string; label: string}
export type AvailableAction = {action: ActionName; label: string; description: string; allowed: boolean; disabled_reason?: string | null; reasons: ActionReason[]; requires_note: boolean; accepts_receipt: boolean; danger: boolean; primary: boolean}
export type ActionRequest = {id: string; request_id: string; action: ActionName; reason_code: string; reason_label: string; note?: string | null; new_receipt_num?: string | null; expected_revision: number; requested_by: string; status: 'pending' | 'recorded' | 'accepted' | 'failed' | 'completed'; created_at: string; acknowledged_at?: string | null; acknowledgement_detail?: string | null}
export type Workflow = {status: string; assigned_to: string; version: number; updated_at: string; last_action_id?: string | null; requests?: ActionRequest[]; available_actions?: AvailableAction[]}
export type Document = {id: string; source_system: string; external_id: string; revision: number; current_revision: number; is_current: boolean; status: Status; company: string; invoice: Invoice; receipt?: Receipt | null; updated_at: string; pdf: {available: boolean; pages: number | null; revision: number | null; stale: boolean}; workflow: Workflow; snapshot: Snapshot; revisions?: RevisionSummary[]}
export type DocumentList = {items: Document[]; total: number; page: number; page_size: number; counts: Partial<Record<Status, number>>; companies: string[]; sources: string[]}
export type Activity = {id: string; kind: string; detail: string; created_at: string}
export type AuditEvent = Activity & {document_id: string; invoice_num: string; external_id: string; company: string; source_system: string}
export type AuditPage = {items: AuditEvent[]; total: number; page: number; page_size: number; kinds: string[]}
export type SessionInfo = {workspace: string; mode: string; permissions: string[]; rbac: boolean; capabilities: Record<string, boolean>}
